-- Create the USERS table
CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fullname VARCHAR2(100) NOT NULL,
  email VARCHAR2(100) NOT NULL UNIQUE,
  password VARCHAR2(255) NOT NULL
);

-- Insert sample user (password should be hashed in real usage)
INSERT INTO users (fullname, email, password)
VALUES ('Ann Perera', 'ann@example.com', 'admin123');

SELECT * FROM users;

DESCRIBE users;

SELECT owner, table_name FROM all_tables WHERE table_name = 'USERS';

GRANT INSERT ON SYSTEM.users TO system;
GRANT SELECT, INSERT ON SYSTEM.users TO system;
SELECT table_name FROM all_tables WHERE table_name = 'USERS';
GRANT ALL PRIVILEGES ON users TO system;
GRANT SELECT, INSERT, UPDATE, DELETE ON users TO system;
SELECT table_name FROM user_tables;







